ALTER TABLE grievances ADD COLUMN IF NOT EXISTS idempotency_key VARCHAR(128) UNIQUE;
ALTER TABLE grievances ADD COLUMN IF NOT EXISTS text_cipher TEXT;
ALTER TABLE grievances ADD COLUMN IF NOT EXISTS channel VARCHAR(32) DEFAULT 'WEB';
